language: c

os:
  - osx
  - linux

dist: xenial

compiler:
  - gcc
  - clang
matrix:
    exclude:
        - os: osx
          compiler: gcc

script:
  - make ci_without_ffmpeg
  - ./caption-inspector --version
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install ffmpeg cairo && pip install pytest; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./travis_ffmpeg_install.sh; fi
  - make caption-inspector
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - ./caption-inspector --version
